Repository Ogu-Family/fiml-backend, pull requests merged in 2024-01, with the labels that each got.

#30 26 후원 생성삭제 api 구현
  src/main/java/kpl/fiml/payment/application/PaymentService.java
  src/main/java/kpl/fiml/payment/dto/PaymentCreateRequest.java
  src/main/java/kpl/fiml/project/domain/Project.java
  src/main/java/kpl/fiml/project/domain/Reward.java
  src/main/java/kpl/fiml/project/domain/RewardRepository.java
  src/main/java/kpl/fiml/sponsor/application/SponsorService.java
  src/main/java/kpl/fiml/sponsor/domain/Sponsor.java
  src/main/java/kpl/fiml/sponsor/domain/SponsorRepository.java
  src/main/java/kpl/fiml/sponsor/dto/SponsorCreateRequest.java
  src/main/java/kpl/fiml/sponsor/dto/SponsorCreateResponse.java
  src/main/java/kpl/fiml/sponsor/dto/SponsorDeleteResponse.java
  src/main/java/kpl/fiml/sponsor/presentation/SponsorController.java
Labels: feature

#35 27 연관관계 매핑 및 수정
  src/main/java/kpl/fiml/comment/application/CommentService.java
  src/main/java/kpl/fiml/comment/domain/Comment.java
  src/main/java/kpl/fiml/comment/domain/CommentRepository.java
  src/main/java/kpl/fiml/comment/dto/CommentCreateRequest.java
  src/main/java/kpl/fiml/comment/dto/CommentCreateResponse.java
  src/main/java/kpl/fiml/comment/dto/CommentDto.java
  src/main/java/kpl/fiml/comment/dto/CommentUpdateRequest.java
  src/main/java/kpl/fiml/comment/dto/CommentUpdateResponse.java
  src/main/java/kpl/fiml/comment/presentation/CommentController.java
  src/main/java/kpl/fiml/global/config/WebSecurityConfig.java
  src/main/java/kpl/fiml/notice/application/NoticeService.java
  src/main/java/kpl/fiml/notice/domain/NoticeRepository.java
  src/main/java/kpl/fiml/notice/dto/NoticeCreateRequest.java
  src/main/java/kpl/fiml/notice/dto/NoticeDeleteResponse.java
  src/main/java/kpl/fiml/notice/dto/NoticeUpdateRequest.java
  src/main/java/kpl/fiml/notice/dto/NoticeUpdateResponse.java
  src/main/java/kpl/fiml/notice/presentation/NoticeController.java
  src/main/java/kpl/fiml/user/application/UserDetailServiceImpl.java
  src/main/java/kpl/fiml/user/application/UserService.java
  src/main/java/kpl/fiml/user/domain/User.java
  src/main/java/kpl/fiml/user/domain/UserRepository.java
  src/main/java/kpl/fiml/user/dto/UserCreateRequest.java
  src/main/java/kpl/fiml/user/dto/UserDeleteResponse.java
  src/main/java/kpl/fiml/user/dto/UserDto.java
  src/main/java/kpl/fiml/user/dto/UserUpdateRequest.java
  src/main/java/kpl/fiml/user/dto/UserUpdateResponse.java
  src/main/java/kpl/fiml/user/presentation/UserController.java
Labels: feature

#33 32 프로젝트 리스트 조회 나머지 작업 완료 및 User 연관 설정
  src/main/java/kpl/fiml/project/application/ProjectService.java
  src/main/java/kpl/fiml/project/domain/Project.java
  src/main/java/kpl/fiml/project/domain/ProjectRepositoryQueryImpl.java
  src/main/java/kpl/fiml/project/dto/ProjectDto.java
  src/main/java/kpl/fiml/project/dto/ProjectInitRequest.java
  src/main/java/kpl/fiml/project/dto/ProjectListFindRequest.java
  src/main/java/kpl/fiml/project/presentation/ProjectController.java
  src/main/java/kpl/fiml/user/domain/User.java
Labels: feature

#39 37 user project 연관관계 매핑 및 리팩토링
  src/main/java/kpl/fiml/comment/application/CommentService.java
  src/main/java/kpl/fiml/comment/dto/CommentCreateRequest.java
  src/main/java/kpl/fiml/comment/dto/CommentUpdateRequest.java
  src/main/java/kpl/fiml/comment/presentation/CommentController.java
  src/main/java/kpl/fiml/notice/application/NoticeService.java
  src/main/java/kpl/fiml/notice/domain/Notice.java
  src/main/java/kpl/fiml/notice/domain/NoticeRepository.java
  src/main/java/kpl/fiml/notice/dto/NoticeCreateRequest.java
  src/main/java/kpl/fiml/notice/dto/NoticeCreateResponse.java
  src/main/java/kpl/fiml/notice/dto/NoticeUpdateRequest.java
  src/main/java/kpl/fiml/notice/presentation/NoticeController.java
  src/main/java/kpl/fiml/user/application/UserService.java
  src/main/java/kpl/fiml/user/domain/User.java
  src/main/java/kpl/fiml/user/dto/UserUpdateRequest.java
  src/main/java/kpl/fiml/user/presentation/UserController.java
Labels: feature, refactor

#38 36 팔로우 찜 기능 추가
  src/main/java/kpl/fiml/project/application/ProjectService.java
  src/main/java/kpl/fiml/project/domain/ProjectLike.java
  src/main/java/kpl/fiml/project/domain/ProjectLikeRepository.java
  src/main/java/kpl/fiml/project/presentation/ProjectController.java
  src/main/java/kpl/fiml/user/application/UserService.java
  src/main/java/kpl/fiml/user/domain/Following.java
  src/main/java/kpl/fiml/user/domain/FollowingRepository.java
  src/main/java/kpl/fiml/user/domain/User.java
  src/main/java/kpl/fiml/user/presentation/UserController.java
Labels: feature

#43 40 결제정산후원 리팩토링
  build.gradle
  src/main/java/kpl/fiml/comment/application/CommentService.java
  src/main/java/kpl/fiml/comment/domain/Comment.java
  src/main/java/kpl/fiml/global/common/BaseEntity.java
  src/main/java/kpl/fiml/notice/application/NoticeService.java
  src/main/java/kpl/fiml/notice/domain/Notice.java
  src/main/java/kpl/fiml/payment/application/PaymentService.java
  src/main/java/kpl/fiml/payment/domain/Payment.java
  src/main/java/kpl/fiml/payment/domain/PaymentRepository.java
  src/main/java/kpl/fiml/payment/dto/request/PaymentCreateRequest.java
  src/main/java/kpl/fiml/payment/dto/response/PaymentDto.java
  src/main/java/kpl/fiml/payment/presentation/PaymentController.java
  src/main/java/kpl/fiml/project/domain/ProjectRepository.java
  src/main/java/kpl/fiml/project/domain/RewardRepository.java
  src/main/java/kpl/fiml/settlement/application/SettlementService.java
  src/main/java/kpl/fiml/settlement/dto/response/SettlementDto.java
  src/main/java/kpl/fiml/settlement/presentation/SettlementController.java
  src/main/java/kpl/fiml/sponsor/application/SponsorService.java
  src/main/java/kpl/fiml/sponsor/domain/Sponsor.java
  src/main/java/kpl/fiml/sponsor/domain/SponsorRepository.java
  src/main/java/kpl/fiml/sponsor/dto/request/SponsorCreateRequest.java
  src/main/java/kpl/fiml/sponsor/dto/request/SponsorUpdateRequest.java
  src/main/java/kpl/fiml/sponsor/dto/response/SponsorCreateResponse.java
  src/main/java/kpl/fiml/sponsor/dto/response/SponsorDeleteResponse.java
  src/main/java/kpl/fiml/sponsor/dto/response/SponsorDto.java
  src/main/java/kpl/fiml/sponsor/presentation/SponsorController.java
  src/main/java/kpl/fiml/user/application/UserService.java
  src/main/java/kpl/fiml/user/domain/User.java
Labels: refactor

#48 fix: 순환 참조 해결
  src/main/java/kpl/fiml/payment/application/PaymentService.java
Labels: fix

#50 42 프로젝트리워드 리팩토링 및 세부 기능 구현
  src/main/java/kpl/fiml/project/application/ProjectService.java
  src/main/java/kpl/fiml/project/domain/Project.java
  src/main/java/kpl/fiml/project/domain/ProjectRepository.java
  src/main/java/kpl/fiml/project/domain/ProjectRepositoryQueryImpl.java
  src/main/java/kpl/fiml/project/domain/Reward.java
  src/main/java/kpl/fiml/project/dto/ProjectFundingPlanUpdateRequest.java
  src/main/java/kpl/fiml/project/dto/ProjectImageDto.java
  src/main/java/kpl/fiml/project/dto/ProjectInitRequest.java
  src/main/java/kpl/fiml/project/dto/ProjectListFindRequest.java
  src/main/java/kpl/fiml/project/dto/ProjectRewardDto.java
  src/main/java/kpl/fiml/project/presentation/ProjectController.java
Labels: feature, refactor

#52 45 후원 조회 api 세분화
  src/main/java/kpl/fiml/payment/application/PaymentService.java
  src/main/java/kpl/fiml/project/domain/RewardRepository.java
  src/main/java/kpl/fiml/sponsor/application/SponsorService.java
  src/main/java/kpl/fiml/sponsor/domain/SponsorRepository.java
  src/main/java/kpl/fiml/sponsor/presentation/SponsorController.java
Labels: feature

#54 53 프로젝트 상세 조회 및 삭제 구현
  src/main/java/kpl/fiml/notice/application/NoticeService.java
  src/main/java/kpl/fiml/project/application/ProjectService.java
  src/main/java/kpl/fiml/project/domain/Project.java
  src/main/java/kpl/fiml/project/domain/ProjectRepository.java
  src/main/java/kpl/fiml/project/domain/ProjectRepositoryQuery.java
  src/main/java/kpl/fiml/project/domain/ProjectRepositoryQueryImpl.java
  src/main/java/kpl/fiml/project/dto/request/ProjectBasicInfoUpdateRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectDetailIntroductionUpdateRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectFundingPlanUpdateRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectImageRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectInitRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectListFindRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectRewardRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectRewardUpdateRequest.java
  src/main/java/kpl/fiml/project/dto/response/ProjectDetailResponse.java
  src/main/java/kpl/fiml/project/dto/response/ProjectImageResponse.java
  src/main/java/kpl/fiml/project/dto/response/ProjectInitResponse.java
  src/main/java/kpl/fiml/project/dto/response/ProjectResponse.java
  src/main/java/kpl/fiml/project/dto/response/ProjectRewardResponse.java
  src/main/java/kpl/fiml/project/presentation/ProjectController.java
  src/main/java/kpl/fiml/settlement/application/SettlementService.java
Labels: feature

#56 51 로그아웃 구현 및 user controller 테스트코드 작성
  .gitignore
  src/main/java/kpl/fiml/global/exception/ErrorResponse.java
  src/main/java/kpl/fiml/global/jwt/JwtTokenProvider.java
  src/main/java/kpl/fiml/notice/application/NoticeService.java
  src/main/java/kpl/fiml/notice/domain/Notice.java
  src/main/java/kpl/fiml/user/application/UserDetailServiceImpl.java
  src/main/java/kpl/fiml/user/application/UserService.java
  src/main/java/kpl/fiml/user/domain/User.java
  src/main/java/kpl/fiml/user/dto/request/LoginRequest.java
  src/main/java/kpl/fiml/user/dto/request/UserCreateRequest.java
  src/main/java/kpl/fiml/user/exception/EmailNotFoundException.java
  src/main/java/kpl/fiml/user/exception/InvalidEmailException.java
  src/main/java/kpl/fiml/user/exception/InvalidPasswordException.java
  src/main/java/kpl/fiml/user/exception/UserErrorCode.java
  src/main/java/kpl/fiml/user/exception/UserGlobalExceptionHandler.java
  src/main/java/kpl/fiml/user/presentation/UserController.java
  src/main/java/kpl/fiml/user/vo/EmailVo.java
  src/main/java/kpl/fiml/user/vo/PasswordVo.java
  src/test/java/kpl/fiml/user/application/UserServiceTest.java
  src/test/java/kpl/fiml/user/presentation/UserControllerTest.java
Labels: refactor, test

#59 55 후원 테스트코드 작성
  build.gradle
  src/main/java/kpl/fiml/project/exception/RewardErrorCode.java
  src/main/java/kpl/fiml/project/exception/RewardGlobalExceptionHandler.java
  src/main/java/kpl/fiml/project/exception/RewardNotFoundException.java
  src/main/java/kpl/fiml/sponsor/application/SponsorService.java
  src/main/java/kpl/fiml/sponsor/domain/Sponsor.java
  src/main/java/kpl/fiml/sponsor/dto/request/SponsorCreateRequest.java
  src/main/java/kpl/fiml/sponsor/dto/request/SponsorUpdateRequest.java
  src/main/java/kpl/fiml/sponsor/exception/InvalidTotalAmountException.java
  src/main/java/kpl/fiml/sponsor/exception/SponsorAccessDeniedException.java
  src/main/java/kpl/fiml/sponsor/exception/SponsorErrorCode.java
  src/main/java/kpl/fiml/sponsor/exception/SponsorGlobalExceptionHandler.java
  src/main/java/kpl/fiml/sponsor/exception/SponsorModifyDeniedException.java
  src/main/java/kpl/fiml/sponsor/exception/SponsorNotFoundException.java
  src/test/java/kpl/fiml/customMockUser/WithCustomMockUser.java
  src/test/java/kpl/fiml/customMockUser/WithCustomMockUserSecurityContextFactory.java
  src/test/java/kpl/fiml/sponsor/application/SponsorServiceTest.java
  src/test/java/kpl/fiml/sponsor/domain/SponsorTest.java
  src/test/java/kpl/fiml/sponsor/presentation/SponsorControllerTest.java
Labels: refactor, test

#63 62 프로젝트 커스텀 예외 적용
  src/main/java/kpl/fiml/project/application/ProjectService.java
  src/main/java/kpl/fiml/project/domain/Project.java
  src/main/java/kpl/fiml/project/domain/ProjectRepositoryQueryImpl.java
  src/main/java/kpl/fiml/project/domain/Reward.java
  src/main/java/kpl/fiml/project/dto/request/ProjectDetailIntroductionUpdateRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectImageRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectRewardUpdateRequest.java
  src/main/java/kpl/fiml/project/dto/response/ProjectResponse.java
  src/main/java/kpl/fiml/project/exception/RewardErrorCode.java
  src/main/java/kpl/fiml/project/exception/project/ProjectAccessException.java
  src/main/java/kpl/fiml/project/exception/project/ProjectDeleteException.java
  src/main/java/kpl/fiml/project/exception/project/ProjectErrorCode.java
  src/main/java/kpl/fiml/project/exception/project/ProjectFieldValueException.java
  src/main/java/kpl/fiml/project/exception/project/ProjectFindConditionException.java
  src/main/java/kpl/fiml/project/exception/project/ProjectFoundException.java
  src/main/java/kpl/fiml/project/exception/project/ProjectFundingException.java
  src/main/java/kpl/fiml/project/exception/project/ProjectGlobalExceptionHandler.java
  src/main/java/kpl/fiml/project/exception/project/ProjectLikeException.java
  src/main/java/kpl/fiml/project/exception/project/ProjectSubmitException.java
  src/main/java/kpl/fiml/project/exception/reward/RewardErrorCode.java
  src/main/java/kpl/fiml/project/exception/reward/RewardFieldValueException.java
  src/main/java/kpl/fiml/project/exception/reward/RewardGlobalExceptionHandler.java
  src/main/java/kpl/fiml/project/exception/reward/RewardNotFoundException.java
  src/main/java/kpl/fiml/sponsor/application/SponsorService.java
  src/test/java/kpl/fiml/project/application/ProjectServiceTest.java
  src/test/java/kpl/fiml/project/domain/ProjectTest.java
  src/test/java/kpl/fiml/project/domain/RewardTest.java
  src/test/java/kpl/fiml/project/presentation/ProjectControllerTest.java
Labels: fix, test

#72 71 swagger 초기 세팅
  build.gradle
  src/main/java/kpl/fiml/global/config/SwaggerConfig.java
  src/main/java/kpl/fiml/payment/dto/response/PaymentDto.java
  src/main/java/kpl/fiml/payment/presentation/PaymentController.java
Labels: feature

#70 65 정산 테스트 및 예외 처리
  src/main/java/kpl/fiml/settlement/application/SettlementService.java
  src/main/java/kpl/fiml/settlement/exception/SettlementAccessDeniedException.java
  src/main/java/kpl/fiml/settlement/exception/SettlementErrorCode.java
  src/main/java/kpl/fiml/settlement/exception/SettlementGlobalExceptionHandler.java
  src/main/java/kpl/fiml/settlement/exception/SettlementNotFoundException.java
  src/test/java/kpl/fiml/customMockUser/WithCustomMockUser.java
  src/test/java/kpl/fiml/customMockUser/WithCustomMockUserSecurityContextFactory.java
  src/test/java/kpl/fiml/settlement/application/SettlementServiceTest.java
  src/test/java/kpl/fiml/settlement/presentation/SettlementControllerTest.java
Labels: refactor, test

#74 69 notice 단위테스트 작성
  src/main/java/kpl/fiml/comment/application/CommentService.java
  src/test/java/kpl/fiml/comment/application/CommentServiceTest.java
  src/test/java/kpl/fiml/comment/domain/CommentTest.java
  src/test/java/kpl/fiml/notice/application/NoticeServiceTest.java
  src/test/java/kpl/fiml/notice/domain/NoticeTest.java
Labels: test

#77 76 project swagger 적용
  src/main/java/kpl/fiml/project/dto/request/ProjectBasicInfoUpdateRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectDetailIntroductionUpdateRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectFundingPlanUpdateRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectImageRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectInitRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectListFindRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectRewardRequest.java
  src/main/java/kpl/fiml/project/dto/request/ProjectRewardUpdateRequest.java
  src/main/java/kpl/fiml/project/exception/project/ProjectGlobalExceptionHandler.java
  src/main/java/kpl/fiml/project/presentation/ProjectController.java
Labels: docs

#79 Project Controller 테스트 수정
  src/test/java/kpl/fiml/TestDataFactory.java
  src/test/java/kpl/fiml/project/presentation/ProjectControllerTest.java
Labels: fix

#81 80 유저 팔로우 테스트 코드 작성
  src/main/java/kpl/fiml/user/application/UserService.java
  src/main/java/kpl/fiml/user/exception/FollowException.java
  src/main/java/kpl/fiml/user/exception/UserErrorCode.java
  src/test/java/kpl/fiml/user/application/UserServiceTest.java
  src/test/java/kpl/fiml/user/presentation/UserControllerTest.java
Labels: test

#82 75 user 스웨거 적용 및 리펙토링
  src/main/java/kpl/fiml/comment/dto/CommentDto.java
  src/main/java/kpl/fiml/comment/dto/request/CommentCreateRequest.java
  src/main/java/kpl/fiml/comment/dto/request/CommentUpdateRequest.java
  src/main/java/kpl/fiml/comment/dto/response/CommentCreateResponse.java
  src/main/java/kpl/fiml/comment/dto/response/CommentDeleteResponse.java
  src/main/java/kpl/fiml/comment/dto/response/CommentUpdateResponse.java
  src/main/java/kpl/fiml/comment/presentation/CommentController.java
  src/main/java/kpl/fiml/global/config/WebSecurityConfig.java
  src/main/java/kpl/fiml/notice/dto/NoticeDto.java
  src/main/java/kpl/fiml/notice/dto/request/NoticeCreateRequest.java
  src/main/java/kpl/fiml/notice/dto/request/NoticeUpdateRequest.java
  src/main/java/kpl/fiml/notice/dto/response/NoticeCreateResponse.java
  src/main/java/kpl/fiml/notice/dto/response/NoticeDeleteResponse.java
  src/main/java/kpl/fiml/notice/dto/response/NoticeUpdateResponse.java
  src/main/java/kpl/fiml/notice/presentation/NoticeController.java
  src/main/java/kpl/fiml/user/dto/UserDto.java
  src/main/java/kpl/fiml/user/dto/request/LoginRequest.java
  src/main/java/kpl/fiml/user/dto/request/UserCreateRequest.java
  src/main/java/kpl/fiml/user/dto/request/UserUpdateRequest.java
  src/main/java/kpl/fiml/user/dto/response/LoginResponse.java
  src/main/java/kpl/fiml/user/dto/response/UserCreateResponse.java
  src/main/java/kpl/fiml/user/dto/response/UserDeleteResponse.java
  src/main/java/kpl/fiml/user/dto/response/UserUpdateResponse.java
  src/main/java/kpl/fiml/user/presentation/UserController.java
Labels: refactor, docs

#83 73 결제정산후원 swagger 적용 및 테스트 보완
  src/main/java/kpl/fiml/settlement/dto/response/SettlementDto.java
  src/main/java/kpl/fiml/settlement/presentation/SettlementController.java
  src/main/java/kpl/fiml/sponsor/dto/request/SponsorCreateRequest.java
  src/main/java/kpl/fiml/sponsor/dto/request/SponsorUpdateRequest.java
  src/main/java/kpl/fiml/sponsor/dto/response/SponsorCreateResponse.java
  src/main/java/kpl/fiml/sponsor/dto/response/SponsorDeleteResponse.java
  src/main/java/kpl/fiml/sponsor/dto/response/SponsorDto.java
  src/main/java/kpl/fiml/sponsor/presentation/SponsorController.java
  src/test/java/kpl/fiml/payment/presentation/PaymentControllerTest.java
  src/test/java/kpl/fiml/settlement/presentation/SettlementControllerTest.java
  src/test/java/kpl/fiml/sponsor/application/SponsorServiceTest.java
  src/test/java/kpl/fiml/sponsor/presentation/SponsorControllerTest.java
Labels: refactor, docs

#85 84 결제정산후원 컨트롤러 테스트 tear down 추가
  src/test/java/kpl/fiml/payment/presentation/PaymentControllerTest.java
  src/test/java/kpl/fiml/settlement/presentation/SettlementControllerTest.java
  src/test/java/kpl/fiml/sponsor/presentation/SponsorControllerTest.java
Labels: test
